#[derive(Debug, PartialEq)]
pub enum Token {
    Ident(String),
    ValuePair(f32, f32),
    Arrow,
    TildeArrow,
    WideArrow,
    Assign,
    Comma,
    Plus,
    LParen,
    RParen,
    LCurly,
    RCurly,
    Pipe,
    Slash,
    LBracket,
    RBracket,
    LWideBracket,
    RWideBracket,
    QuestionMark,
    Semicolon,
    Section,
    Ampersand,
}